import { createKozo, type Kozo } from './app.js';
import type { KozoConfig, Services } from './types.js';

/** Tells the Kozo CLI which type to inject into `KozoServices` (auto-generated `.kozo/types.d.ts`). */
export interface KozoAppTypesRef {
  /** Module path relative to project root, e.g. `src/lib/services/index.js` */
  from: string;
  /** Exported interface name, e.g. `AppServices` */
  name: string;
}

export interface KozoAppHooks<TServices extends Services> {
  app: Kozo<TServices>;
  services: TServices;
}

export interface KozoAppDefinition<
  TServices extends Services = Services,
  TScoped extends Record<string, unknown> = Record<string, never>,
> {
  routesDir: string;
  services: () => TServices | Promise<TServices>;
  types: KozoAppTypesRef;
  configure?: (ctx: KozoAppHooks<TServices>) => void | Promise<void>;
  onReady?: (ctx: Pick<KozoAppHooks<TServices>, 'app'>) => void | Promise<void>;
  kozo?: Omit<KozoConfig<TServices, TScoped>, 'services' | 'routesDir'>;
  build: () => Promise<Kozo<TServices, TScoped>>;
}

export interface DefineKozoAppOptions<
  TServices extends Services,
  TScoped extends Record<string, unknown> = Record<string, never>,
> {
  routesDir?: string;
  services: () => TServices | Promise<TServices>;
  types: KozoAppTypesRef;
  configure?: (ctx: KozoAppHooks<TServices>) => void | Promise<void>;
  onReady?: (ctx: Pick<KozoAppHooks<TServices>, 'app'>) => void | Promise<void>;
}

/**
 * Declare a Kozo app — used in `kozo.config.ts`.
 * The CLI reads {@link KozoAppTypesRef} and generates `.kozo/types.d.ts` so route
 * handlers get typed `ctx.services` without manual module augmentation.
 */
export function defineKozoApp<
  TServicesFn extends () => Services | Promise<Services>,
  TScoped extends Record<string, unknown> = Record<string, never>,
>(
  options: DefineKozoAppOptions<Awaited<ReturnType<TServicesFn>>, TScoped> &
    Omit<KozoConfig<Awaited<ReturnType<TServicesFn>>, TScoped>, 'services' | 'routesDir'> & {
      services: TServicesFn;
    },
): KozoAppDefinition<Awaited<ReturnType<TServicesFn>>, TScoped> {
  type TServices = Awaited<ReturnType<TServicesFn>>;
  const { routesDir = './src/routes', services, types, configure, onReady, ...kozo } = options;

  const definition: KozoAppDefinition<TServices, TScoped> = {
    routesDir,
    services,
    types,
    configure,
    onReady,
    kozo: kozo as Omit<KozoConfig<TServices, TScoped>, 'services' | 'routesDir'>,
    build: () => buildKozoApp(definition),
  };

  return definition;
}

/** Bootstrap a app from {@link defineKozoApp}. */
export async function buildKozoApp<
  TServices extends Services,
  TScoped extends Record<string, unknown> = Record<string, never>,
>(definition: KozoAppDefinition<TServices, TScoped>): Promise<Kozo<TServices, TScoped>> {
  const resolved = await definition.services();
  const app = createKozo<TServices, TScoped>({
    ...definition.kozo,
    routesDir: definition.routesDir,
    services: resolved,
  });

  if (definition.configure) {
    await definition.configure({ app, services: resolved });
  }

  await app.loadRoutes();

  if (definition.onReady) {
    await definition.onReady({ app });
  }

  return app;
}

/** Generate `.kozo/types.d.ts` source (CLI / Node). */
export async function renderKozoTypesDts(
  types: KozoAppTypesRef,
  projectRoot: string,
): Promise<string> {
  const path = await import('node:path');
  const from = path.join(projectRoot, '.kozo', 'types.d.ts');
  const to = path.join(projectRoot, types.from);
  let rel = path.relative(path.dirname(from), to).replace(/\\/g, '/');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  const importPath = rel.replace(/\.ts$/, '.js');

  return `// Auto-generated by Kozo — do not edit.
import type { ${types.name} } from '${importPath}';

declare module '@kozojs/core' {
  interface KozoServices extends ${types.name} {}
}
`;
}

export const KOZO_TYPES_CANDIDATES = [
  'src/kozo.types.ts',
  'src/kozo.types.js',
  'kozo.types.ts',
] as const;

export const KOZO_CONFIG_CANDIDATES = [
  'kozo.config.ts',
  'kozo.config.js',
  'src/kozo.config.ts',
  'src/kozo.config.js',
] as const;

export const KOZO_TYPES_OUTPUT = '.kozo/types.d.ts';
